FROM ros:jazzy-ros-base

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
        python3-colcon-common-extensions \
        python3-vcstool \
        python3-rosdep \
        libusb-1.0-0-dev \
        libopencv-dev \
        pkg-config \
        terminator \
        ros-jazzy-cv-bridge \
        && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true && rosdep update

RUN mkdir -p /root/jazzy_ws/src
COPY robotiq_tsf /root/jazzy_ws/src/robotiq_tsf


# Build the workspace
RUN /bin/bash -lc "source /opt/ros/jazzy/setup.bash && \
    cd /root/jazzy_ws  && \
    colcon build --symlink-install"


# Source setup scripts
RUN echo 'source /opt/ros/jazzy/setup.bash' >> ~/.bashrc && \
    echo 'source ~/jazzy_ws/install/setup.bash' >> ~/.bashrc

WORKDIR /root/jazzy_ws

ENTRYPOINT ["/bin/bash"]